---
# file: tasks/use-apt.yml
#
# Configure td-agent from APT repository.
#
# @see http://docs.fluentd.org/articles/install-by-deb
# @see http://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh
#

- name: install add-apt-repository binary for Ansible to work
  apt: name=python-software-properties state=present update_cache=yes

- name: add APT signing key for td-agent
  apt_key: url=http://packages.treasuredata.com/GPG-KEY-td-agent state=present

- name: add td-agent repository
  apt_repository: repo='deb http://packages.treasuredata.com/2/{{ ansible_distribution|lower }}/{{ ansible_distribution_release|lower }}/ {{ ansible_distribution_release|lower }} contrib' state=present


- name: install td-agent
  apt: name=td-agent  update_cache=yes  state=present force=yes
  when: tdagent_version is not defined

- name: install td-agent
  apt: name="td-agent={{ tdagent_version }}*"  update_cache=yes  state=present force=yes
  when: tdagent_version is defined



- name: install libcurl and make for compiling plugins
  apt: name={{ item }}  state=present update_cache=yes
  with_items:
    - libcurl4-gnutls-dev
    - build-essential
  when: tdagent_plugins is defined or tdagent_plugins_versions is defined



- name: set INIT status and start
  service: name=td-agent state=started enabled=yes
  when: tdagent_use_service|bool

- name: set INIT status (SysV style)
  shell: update-rc.d td-agent defaults
  when: not tdagent_use_service|bool
