---
# file: tasks/use-yum.yml
#
# Configure td-agent from YUM repository.
#
# @see http://docs.fluentd.org/articles/install-by-rpm
# @see http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh
#


- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present



- name: add GPG key from Treasure Data, Inc
  command: rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent
#  rpm_key: key=https://packages.treasuredata.com/GPG-KEY-td-agent validate_certs=no state=present

- name: add official repository
  copy: src=../files/td.repo dest=/etc/yum.repos.d/td.repo

- name: install td-agent
  yum: name=td-agent  update_cache=yes  state=present
  when: tdagent_version is not defined

- name: install td-agent
  yum: name="td-agent-{{ tdagent_version }}*"  update_cache=yes  state=present
  when: tdagent_version is defined


- name: install gcc and libcurlXXX for compiling plugins
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - libcurl
    - libcurl-devel
  when: tdagent_plugins is defined or tdagent_plugins_versions is defined


- name: set INIT status and start
  service: name=td-agent state=started enabled=yes
  when: tdagent_use_service|bool

- name: set INIT status (SysV style)
  command: /sbin/chkconfig td-agent on
  when: not tdagent_use_service|bool

#- name: set INIT status (SysV style)
#  action: shell chkconfig --add td-agent
#  action: shell chkconfig --level 345 td-agent on
